# netlify.toml
[[redirects]]
  from = "/api/*"
  to   = "https://skillping-server.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { 
    # para que la petición lleve y reciba cookies
    "Access-Control-Allow-Credentials" = "true" 
  }
