[build]
  command = "npm run build"
  publish = "dist/ProyectoTfg_A16_v2" 

[[redirects]]
  from   = "/api/*"
  to     = "https://skillping-server.onrender.com/api/:splat"
  status = 200
  force  = true
  headers = { "Access-Control-Allow-Credentials" = "true" }

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  force  = true